import vehicle from './vehicle.js';
import auth from './auth.js';
import vendor from './vendor.js';
import floorPlan from './floorPlan.js';
import { Router } from 'express';
import customer from './customer.js';
import sales from './sales.js';
import netTradeIn from './netTradeIn.js';
import profile from './profile.js';
import accounting from './accounting.js';
import dashboard from './dashboard.js';

const router = Router();
router.use('/auth', auth);
router.use('/vendor', vendor);
router.use('/vehicle', vehicle);
router.use('/floorPlan', floorPlan);
router.use('/customer', customer);
router.use('/sales', sales);
router.use('/net-trade-in', netTradeIn);
router.use('/user', profile);
router.use('/accounting', accounting);
router.use('/dashboard', dashboard);
export default router;
