import mongoose from 'mongoose';

const { Schema } = mongoose;

const vendorSchema = new Schema(
  {
    category: {
      type: String,
      enum: [
        'Auction - AU',
        'Company - COM',
        'Wholesale - WS',
        'Dealer - DL',
        'Consignment - CT',
        'Private Seller - PS',
        'Manufacturer - MR',
        'Rental Company - RC',
        'Repossession - RE',
        'Trade-In - TI',
      ],
      required: true,
    },
    name: { type: String, required: true },
    street: String,
    zip: String,
    city: String,
    state: {
      type: String,
      enum: [
        'Alabama',
        'Alaska',
        'Arizona',
        'Arkansas',
        'California',
        'Colorado',
        'Connecticut',
        'Delaware',
        'Florida',
        'Georgia',
        'Hawaii',
        'Idaho',
        'Illinois',
        'Indiana',
        'Iowa',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Maine',
        'Maryland',
        'Massachusetts',
        'Michigan',
        'Minnesota',
        'Mississippi',
        'Missouri',
        'Montana',
        'Nebraska',
        'Nevada',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'New York',
        'North Carolina',
        'North Dakota',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Pennsylvania',
        'Rhode Island',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Vermont',
        'Virginia',
        'Washington',
        'West Virginia',
        'Wisconsin',
        'Wyoming',
      ],
    },
    primaryContactNumber: String,
    contactPerson: String,
    alternativeContactNumber: String,
    email: {
      type: String,
      unique: true,
      required: true,
    },
    accountNumber: String,
    taxIdOrSSN: String,
    billofsales: {
      type: String,
      default: '',
    },
    note: String,
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
    vendorId: {
      type: String,
    },
  },
  { timestamps: true }
);

const vendor = mongoose.model('vendor', vendorSchema);
export default vendor;
